from __future__ import annotations

from pathlib import Path


def write_pymol_script(
    pml_path: Path,
    pdb_path: Path,
    node_labels: list[str],
    centrality: dict[int, float],
    top_pairs: list[tuple[str, str, float]],
    path_edges: list[tuple[str, str]] | None = None,
) -> None:
    """Write a PyMOL .pml script that colors residues by centrality and shows allosteric pairs."""
    max_c = max(centrality.values(), default=1.0) or 1.0
    lines: list[str] = [
        "# Generated by allostery analyze",
        f'load "{pdb_path.resolve()}"',
        "hide everything",
        "show cartoon",
        "color white",
        "",
        "# Color residues by betweenness centrality (white=low, red=high)",
        "alter all, b=0.0",
    ]
    for idx, label in enumerate(node_labels):
        chain, resi = _parse_label(label)
        norm_c = centrality.get(idx, 0.0) / max_c
        lines.append(f"alter chain {chain} and resi {resi} and name CA, b={norm_c:.4f}")
    lines += [
        "spectrum b, white_red, minimum=0.0, maximum=1.0",
        "",
        "# Top allosteric pairs",
    ]
    for k, (label_i, label_j, _score) in enumerate(top_pairs, 1):
        chain_i, resi_i = _parse_label(label_i)
        chain_j, resi_j = _parse_label(label_j)
        si = f"(chain {chain_i} and resi {resi_i} and name CA)"
        sj = f"(chain {chain_j} and resi {resi_j} and name CA)"
        lines.append(f"distance pair_{k}, {si}, {sj}")
    lines += ["color yellow, pair_*", ""]
    if path_edges:
        lines.append("# Allosteric path")
        for k, (src, dst) in enumerate(path_edges, 1):
            cs, rs = _parse_label(src)
            cd, rd = _parse_label(dst)
            ss = f"(chain {cs} and resi {rs} and name CA)"
            sd = f"(chain {cd} and resi {rd} and name CA)"
            lines.append(f"distance path_{k}, {ss}, {sd}")
        lines += ["color cyan, path_*", ""]
    lines.append("zoom")
    pml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _parse_label(label: str) -> tuple[str, str]:
    """Parse 'A:12 GLY' → ('A', '12')."""
    chain, rest = label.split(":", 1)
    resi = rest.split()[0]
    return chain, resi


__all__ = ["write_pymol_script"]
